
version: 2

models:
  - name: analytics_messages
    columns:
      - name: source_file
        tests:
          - unique
          - not_null
      - name: message
        tests:
          - not_null