
name: DataOps CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 dbt-core dbt-sqlite pandas azure-storage-blob

    - name: Run Linters (Flake8)
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # Initialisation du profil DBT pour le serveur GitHub
    - name: Setup DBT Profile
      run: |
        mkdir -p ~/.dbt
        echo "dataops_project:" > ~/.dbt/profiles.yml
        echo "  outputs:" >> ~/.dbt/profiles.yml
        echo "    dev:" >> ~/.dbt/profiles.yml
        echo "      type: sqlite" >> ~/.dbt/profiles.yml
        echo "      threads: 1" >> ~/.dbt/profiles.yml
        echo "      database: 'database/dataops.db'" >> ~/.dbt/profiles.yml
        echo "      schema: 'main'" >> ~/.dbt/profiles.yml
        echo "  target: dev" >> ~/.dbt/profiles.yml

    # Exécution des transformations et des tests de qualité sur GitHub
    - name: Run DBT Models
      run: dbt run --project-dir dataops_dbt --profiles-dir ~/.dbt

    - name: Run DBT Tests
      run: dbt test --project-dir dataops_dbt --profiles-dir ~/.dbt